name: 'Trivy Scan'
description: 'Run Trivy scan using aquasecurity/trivy-action'
inputs:
  image:
    description: 'Docker image to scan'
    required: true
  severity:
    description: 'Severity levels to report'
    required: false
    default: 'LOW,MEDIUM,HIGH,CRITICAL'
  ignorefile:
    description: 'Path to .gitignore file'
    required: false
    default: '.gitignore'
outputs:
  report:
    description: 'Path to the Trivy scan report'
runs:
  using: 'composite'
  steps:
    - name: Run Trivy scan
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        severity: CRITICAL,HIGH
        ignorefile: ${{ inputs.ignorefile }}
    - name: Set output
      shell: bash
      run: echo "report=${{ steps.trivy-scan.outputs.report }}" >> $GITHUB_OUTPUT
