name: 'Trivy Scan'
description: 'Run Trivy scan using aquasecurity/trivy-action'
inputs:
  image:
    description: 'Docker image to scan'
    required: true
  severity:
    description: 'Severity levels to report'
    required: false
    default: 'LOW,MEDIUM,HIGH,CRITICAL'
  ignorefile:
    description: 'Path to .trivyignore file'
    required: false
    default: '.trivyignore'
  scan-path:
    description: 'Scan path'
    required: false
outputs:
  report:
    description: 'Path to the Trivy scan report'
    value:
runs:
  using: 'composite'
  steps:
    - name: Run Trivy scan
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        severity: ${{ inputs.severity }}
        scan-ref: ${{ inputs.scan-path }}
    - name: Set output
      shell: bash
      run: echo "report=${{ steps.trivy-scan.outputs.report }}" >> $GITHUB_OUTPUT
